### ISSUE TITLE
Improvement on the DAG implementation complexity

### ISSUE THREAD

**Issue by JosephMarotte** [AdaCore/e3-core#434]
Noticed the following things on the DAG implementation which may improve the complexity / runtime if changed (where G(V, E), v are the vertices, and e the edges).

- In the `get_closure` and `check` function a BFS is done. However, the call to `closure - visited` in these function may have a linear time complexity in the size of closure, For some kinds of DAG it can leads to a O(|V|^2 + |E|) complexity instead of O(|V| + |E|) for exemple calling `get_closure(n)` on the following graph :
```
1
  \
    2
     \
       ...
         \
           n
```

- In a similar way, the `shortest_path` functions is using the dijskstra algorithm O(|E| + |V|*log(|V|)) but could use a BFS since the graph is unweighted. Dijkstra may be used for some other reason, but even if it's the case the implementation can be improved. The overall complexity of the Dijkstra algorithm greatly depends of the function that we could call `find_min` to find the vertex of minimal distance from the starting vertex of the algorithm. Usually the data structure used for this is a `priority_queue`. The data structure used here is a `set` and the following call is `u = min(unvisited, key=lambda x: dist[x])` is in linear time. In some case may result in a O(|V|^2 + |E|) time complexity again, it's the case for the example above if we want to find `shortest_path(1, n)`.

- The `add_vertex` function always call `update_vertex` function with `enable_check = false`. Because `update_vertex` always set the `__has_cycle` value to `None` with the call to the `set_predecessors` function (which reset sucessors and cycle_check) it means the call to `check` the next time we add a vertex will always do all the work again (checking for a cycle in the graph which is O(|V| + |E|). However in some cases we may not need to do all this work : it's the case when we add a vertex (if a cycle is created it means there is a path to the added vertex but then this vertex was already in the graph and `add_vertex` would have thrown a DAGError). It's also the case when a vertex is updated but no predecessors is added (no edges are added so it is not possible for a cycle to be created).

- The `__vertex_successors` value is set to `{}` every time `set_predecessors` is called and then the next call to `get_successors` will have a O(|V| + |E|) time complexity. Instead of invalidating the global dictionnary of successors one may just want to propagate the change to it.

**Comment by enzbang** [comment]
Hi @JosephMarotte thank you for your suggestions!

I'll let @Nikokrock look at your proposition.

``add_vertex`` should not be used when performance is important, I thought we had added a comment in the docstring but apparently we did not, so we should at least document that this will have a bad impact on performance when many ``add_vertex`` calls are done. In many cases you want to check for cycle only once all vertices have been added.

For ``set_predecessors`` that's indeed documented, we could do better but have not spent the time because it was not important for our use cases.

**Comment by Nikokrock** [comment]
I have submitted a change for get_closure and documented to use update_vertex rather than add_vertex to speed up insertion

(change #437)

I don't have time to review for the moment shortest_path implementation and computation of successors. Will do that later. In case you have specific changes in mind do not hesitate to make a pull request. We will gladly review it
